
local inputs = {
"uqyoeiznvmzrstpkgnsacjxwld",
"uqloeizfvmbrstpkgndacjxwyd",
"dqgoeizfbmbrstpkgnhacjxwld",
"uqyjeizfvmbrstpygntacjxwld",
"uqyoeizfhmbrstppbnhacjxwld",
"uqyoeizfvmbrstpkschanjxwld",
"uqyoeizfvtbrstpkgnmazjxwld",
"uqyoeizfvmyrstpzgnhacjxsld",
"udtoeizfvmbrttpkgnhacjxwld",
"uqyneizfvmbratpognhacjxwld",
"uqyoeizfvmbrstpkunhaajxnld",
"uqyteizfvmbrstpkgnhzcnxwld",
"hqyteuzfvmbrstpkgnhacjxwld",
"uqyoeizyvmbrsdpkgnhacdxwld",
"uqyoeizfibbrsepkgnhacjxwld",
"uqxoeizfvmbrstpkgnhaxjjwld",
"iqaoeizfvmbrstpkrnhacjxwld",
"uqyoeizpvvbrstpkghhacjxwld",
"aqyoeizfvmbrstpbgnhfcjxwld",
"uqyonfzfvmbrstpkgnhacjgwld",
"uqyoeizovmhrstpkgnhacjxwvd",
"uqyoegzfvmbrstpkgnfacjxrld",
"uqyoeizfvmbrstpjgnwacjxwdd",
"uqyogiifumbrstpkgnhacjxwld",
"uqyorizfvmbrstpkgnhaezxwld",
"uqyoexdfvmbretpkgnhacjxwld",
"uqyoeizfvmbrstpkgwhlcjxzld",
"uqyoeibfvmbrstpggnhzcjxwld",
"udyoeizfvmbrstppwnhacjxwld",
"ufyoeizfvmhrstpkgnfacjxwld",
"aqyoeftfvmbrstpkgnhacjxwld",
"uhyoeivfvmbrstpkgnhadjxwld",
"uqyoeizfvmbrstpkgmhacjxhud",
"uqyfeizfvmbrstpkgnhkljxwld",
"uqyoeibfvmbrstpkgbhazjxwld",
"uqyceizfvnbrslpkgnhacjxwld",
"uqyoeizfvmirstpkonhacaxwld",
"fqyooizfvmbrstpkgnhacjxwlq",
"uqydeizfvmbgstpugnhacjxwld",
"uqyoiizfvmbrstpkgnhacjalld",
"uqyivizfvmbrstpkgnhocjxwld",
"uqyoeizfvmbrstpngnhjcjxwtd",
"uqyoeizfvmbrstpkynhrcexwld",
"ugmfeizfvmbrstpkgnhacjxwld",
"uqyoeizrvmbrstpkwnhycjxwld",
"uqyoeiyfvmbrstpkgnlacjxwwd",
"unyoeizfvmbrstrkgnhadjxwld",
"uqyoeizhvmbrstpkgnhacjawlz",
"uqyoeazfvmbrstpwgnhacjxwlp",
"uqyoeiznvmbastpkgnhaccxwld",
"kqyoeisfvmbrstikgnhacjxwld",
"uqyoeizfvlxrstpmgnhacjxwld",
"uqyoeiofvmbrstpkgniacjxwll",
"uqyoeizfvmbrswpegnhacixwld",
"uqyoeizfvmarstlkgnhanjxwld",
"uuyoeizfvmbrstykgnhacjxwbd",
"uqyoeizfvmbpstxkgnhacjxwlu",
"uqyoqizfvmbrsspkgnhacjpwld",
"uqyoeizfvmzrstnkgnhacjgwld",
"uqyoeizfvmbrstrcgnhacjxwud",
"uqyoeizfvmbrstpkgnuacxxwsd",
"cqyoeizfvmbrscpkgnhacjxwpd",
"sqyoeizfaobrstpkgnhacjxwld",
"uqyoeizfvmbrgtpkgnhacjxbwd",
"uqyoeibhvmbrstpkgnhagjxwld",
"uqyoeizfvcbrstpkgzhactxwld",
"uqkoeizfvmbrstijgnhacjxwld",
"uqroelzfvmbrstpkgmhacjxwld",
"uqyoeizfvmbrsfpcgnhkcjxwld",
"uqyoeizfumgrstpygnhacjxwld",
"uqyozibfvmbrstpkgnhacjwwld",
"uqyoeigfvmbrstpkgjharjxwld",
"uqpoeizfvmbrstpkgnhacjxrcd",
"uqyoeizfvmbrskokgnhqcjxwld",
"uqyoeikfvmbrstpkgehacjxwle",
"uqygeizfvhbrstpkgnqacjxwld",
"lqyoeizfvmbrsvpkgnhacjuwld",
"uqyjeizfvmbectpkgnhacjxwld",
"unyoeizfvmbrstpkgnhzckxwld",
"uqyoeizfvmbrstpkgmoacjxwlm",
"uqfoeizfvmbrutpkgnhacjrwld",
"uqyohizflnbrstpkgnhacjxwld",
"uquoeizfembrstpkgniacjxwld",
"uqyoeizfvmbrytpkgnhbcjkwld",
"pqyoeizfvsbwstpkgnhacjxwld",
"uqyoerzfvmbrstpkxntacjxwld",
"uqyoeizfvmbritpkgnhacjqhld",
"uqyoeisfvmbrstpkglhscjxwld",
"hqyoeizfvmwrstpwgnhacjxwld",
"uqyoeyzrvmbrstpkgnhacjxdld",
"pqyoeozfombrstpkgnhacjxwld",
"uwyosizfvmbrstpkgnhacjrwld",
"uqyoegzfvmbrstekbnhacjxwld",
"uqyoeinfvmirstpkgdhacjxwld",
"uqyoeizfvmbistpkgnobcjtwld",
"uqyoeikfvmbrsepkgnhycjxwld",
"qqyoeiafvmbrstpkgnhacjxold",
"uqbooizfvmbrstpkgnhacjxwdd",
"uquoeizfvmbrswpkgnhatjxwld",
"tqyoejzfvmbrstpkgnhacjxwlv",
"yqyoeizfvmbrsttkgnhakjxwld",
"usyoeizfvmbfstpkgnhkcjxwld",
"gqyocizfvmbrstpkgnhacjbwld",
"mqyoeizfvmbrstpkgnhacjzzld",
"uqyoeczfvmbrotpkgnhacjxwsd",
"jqyoeizfvmkrstpkgnhacaxwld",
"uqyoeirfvmblstpkgnhaijxwld",
"uqpoeirfvmbrstpkgbhacjxwld",
"uqyoiizcvmbrsipkgnhacjxwld",
"uqyoeizfvmbrstekgnhayjywld",
"uqyoeizpvmnrstpkgnhacjxwcd",
"eqyoaizfvmbrstpkgnhacjzwld",
"uqyubizfvmbrltpkgnhacjxwld",
"kqmoeizfvmbrstbkgnhacjxwld",
"uqyoeizfvmkrstpvgnhahjxwld",
"uqyoeizfrmbrsjpkgchacjxwld",
"uqyoeizfvmbrstfkgnhacbxwlx",
"uqyoeizfvmbrstpkbngayjxwld",
"uqyorizfvmbrstpkgghacjxwle",
"oqyoeizfvpkrstpkgnhacjxwld",
"uqyoexzfvmbrscpkgnhacjxwlq",
"uqkoyilfvmbrstpkgnhacjxwld",
"uqyotizfamnrstpkgnhacjxwld",
"uqnoeizfvmbrstpkgnhacdfwld",
"uqyoeizffmbrstqkgnhacuxwld",
"uqyoeizfvmbrzhpkgnhqcjxwld",
"uqyzeizfvmbrsnpkgnracjxwld",
"jhyoeizfvhbrstpkgnhacjxwld",
"uqyohizfvmbrstpkgnqhcjxwld",
"uqyleizfgmbrstlkgnhacjxwld",
"ucyoeizzvmbrstgkgnhacjxwld",
"uqyoeizqvmbrstbkgahacjxwld",
"uqyseizpvkbrstpkgnhacjxwld",
"uqyobizfvmirstpkgnhachxwld",
"uqyoiizfvmbrstpkgnhacwxzld",
"uqyoeizfvmbrstpkgnhafoxsld",
"pqyoeizfvmbrstpkgnhaijxwle",
"uqyoeizfvubrstpkgneacjxcld",
"uqyoeigfumbrstpknnhacjxwld",
"uqyoeiffvmbrstwkgnhacjxxld",
"uqooeizfvmbrstpkgnhacjxilv",
"uqyoeizfvmbrstpkgnhaljirld",
"uqyoeizfvmbistpkgnoacjtwld",
"uqyogizfvmlustpkgnhacjxwld",
"uqyoeizfvmufjtpkgnhacjxwld",
"uqyoeixfvmbrstpugwhacjxwld",
"uqyoeizfrzbrsjpkgnhacjxwld",
"uqyoeizfvmbbsqpkgzhacjxwld",
"uqyoeizovqfrstpkgnhacjxwld",
"uqyieizfvmbrsjpkgnhacjxwzd",
"uqdoeizfvmbrstnkgnqacjxwld",
"usyoohzfvmbrstpkgnhacjxwld",
"uqyoeicfvmbrstpkgnhacgxwtd",
"uqyoeizfvmbrstpkgkhbcjxold",
"fwyoeizfvmbrstpkgnhkcjxwld",
"oqyoeizfvmbrstpkenhacjjwld",
"uqyoeizfvmbrttpkgjhacjhwld",
"uqyoeituvmbrstpkgohacjxwld",
"uqyoeizfvekrslpkgnhacjxwld",
"upyoeizfvmbrstpkgnhjcjxwlb",
"uqyoeiwfvmbrstpkgshacjmwld",
"uqyceizfvmbrstpkgnpazjxwld",
"aqyoeizfvmbrstpkgntacjxwed",
"uqyosizfvmbrsapkgphacjxwld",
"uqyoeizfvmbysipkgnhacjxwls",
"uqyoeicfvmbgstpkgnhacjxwjd",
"uqyoxizfvmbrsggkgnhacjxwld",
"uqyoeizfvbbrhtplgnhacjxwld",
"usyoeizfvmbrstvkgnhacjxwlo",
"uqyleizfvmbrstpkgnhacjxwac",
"uqyoeisfvmbrstpfgnhacjxwdd",
"uqyoeizwvmbvstpkgnhacjxhld",
"uqyoeczfvmbrstpkgnhecjxwlv",
"uqyoeizfvmbrstpkgnhacjueid",
"uqyoeisfvmbrstpkgnhaxjxwzd",
"uqyoeizfvmbrstpkgnhicjmyld",
"ugygeizfvmbrmtpkgnhacjxwld",
"uoyoeiftvmbrstpkgnhacjxwld",
"uqyoeinfvmbrstpkenhacjxwbd",
"xqyoeiofvmbrstpkgnhacjxwlt",
"uqyoeizfvnbrsipkgnhfcjxwld",
"uqyteizfvmbrstpngmhacjxwld",
"uqyoeijfvmbrstpdgnhacjcwld",
"uqyoeizfjmbrstpkgntaclxwld",
"uqyaeizfvmbrstpkgnhajjxwkd",
"uqyoeizfvmbraqpkgnhacjxwlv",
"uqyocizfvmbrstpkqnhrcjxwld",
"uqyoqizfvmbrdtpkenhacjxwld",
"uqyoeicfvwbrstpkknhacjxwld",
"uqyoeizfvmbrstpktnhacjxxlz",
"uqyoeizfvmbhstpkgnhacjmwgd",
"uqyoeizfvmorskpkgnhncjxwld",
"nqyxeezfvmbrstpkgnhacjxwld",
"uqyoeitfvmbrstpksnhicjxwld",
"uqyoeizfmmwrstpkgnhacjxwud",
"uqyoeizfvmmrstpkgnhvcjxwlk",
"uqyoeizfvmbrstpkgihacjxblz",
"uqnoeizfvmwrstpkgnhaujxwld",
"uqyoeizfvlbrsrpkgnhacjxwpd",
"uqyoeizfvmbwstpkgnhvcjxwdd",
"uqyoeixfvlbrstpkgxhacjxwld",
"uqyoeizfvmbjstpmgnhacjxmld",
"uqyoeizyvhbrstpkgnhacjxwzd",
"uqyhepzfvmbrstpkghhacjxwld",
"uqyoetzfvmbrstpkghsacjxwld",
"uqyoeizfvmbrbnpkgnuacjxwld",
"uqyokizfvmbrstpkgnhacqiwld",
"uqyoeizfvmbrstpkgqhacagwld",
"uqyoeizfvnbvstckgnhacjxwld",
"uqyoeizfbmbhstpkjnhacjxwld",
"uqyoeixfvmbrstpkgnegcjxwld",
"uqyoeizfvmbrstpkshlacjxwld",
"uqyoeisfhmbrsnpkgnhacjxwld",
"uqyoekzfvmbrstpkgnhadjxsld",
"uqyoeizfzmyrstckgnhacjxwld",
"uqyoeizpvmbrztpkenhacjxwld",
"uqyopizffmbrstpkgnhacjxuld",
"uqyoeizfvzhrstpkgnhscjxwld",
"uqyoeizfvlbrstskvnhacjxwld",
"uqyohizfvmbrstekgnhacaxwld",
"uqlodizfvmbastpkgnhacjxwld",
"uqyoeizfvubrstpbgnhacjvwld",
"uqnoupzfvmbrstpkgnhacjxwld",
"tqzoeizfvmbrsdpkgnhacjxwld",
"pqyobizfvmbrstphgnhacjxwld",
"uqyweizfvkbrstpkguhacjxwld",
"uqyoexzfvmbrstzktnhacjxwld",
"cqyoeizfvmbrstpkgnhacvxfld",
"uqyoeiefvmbrytpmgnhacjxwld",
"uqyoeizfvmbhstpkgnhmcjpwld",
"uqyoeizfvnbrstpkgnhaczrwld",
"uqyoeibfvnbrstpkgnhacjxvld",
"uqyoeizfvebrsypygnhacjxwld",
"uqyoeikfnmbrstukgnhacjxwld",
"uqyoeizfvmbrsfpkgnhfcdxwld",
"uqyoeizfvmmrstpnbnhacjxwld",
"uqyoeizfvmbrztpegnhacjxwrd",
"pqyoeizfvmbrqtukgnhacjxwld",
"uqyoeizfvmbbstpkgahacjxpld",
"uqsoeizfvmbpstpkgnhatjxwld",
"uqyodizfvmbrsfpkgnhgcjxwld",
"uuyoeizfvmbnstpkgnhacjxbld",
"gqyoeizfvmbrstpkgnhacjqwcd",
"uqyoeizfvmyrotkkgnhacjxwld",
"uqyoeizfvmabstpkgnhacjawld",
"uqyoeizfvmbrstpkglhaszxwld",
"ukyoeizfvmbrstpkgnhacjxtfd",
"uqeoeizfvmbrstpkgnhtnjxwld",
"uqyouizfvmnrstpkgxhacjxwld",
"ugyoeizfvmbrsupygnhacjxwld"
}

twos = 0
threes = 0

for i = 1, #inputs do
    local s = inputs[i]
    local t = {}
    local h2 = false
    local h3 = false
    for j = 1, s:len() do
        local c = s:byte(j)
        t[c] = (t[c] or 0) + 1
    end
    for _,v in pairs(t) do
        if v == 2 then h2 = true end
        if v == 3 then h3 = true end
    end
    if h2 then twos = twos + 1 end
    if h3 then threes = threes + 1 end
end

print("twos ", twos, "threes ", threes, "ck ", twos * threes)

function ab1(x,y) 
    local diffs = false
    for i = 1, x:len() do
        if x:byte(i) ~= y:byte(i) then
            if diffs then return false end
            diffs = true
        end
    end
    return diffs
end

function mb1(x,y) 
    print ("S1 ", x)
    print ("S2 ", y)
    local s = ""
    for i = 1, x:len() do
        if x:byte(i) == y:byte(i) then
            s = s..x:sub(i,i)
        end
    end
    print ("12 ", s)
    return s
end

for i = 1, #inputs do
    for j = i+1, #inputs do
        if ab1(inputs[i], inputs[j]) then
            mb1(inputs[i], inputs[j])
            return
        end
    end
end
